name: Packer Validation
on:
  pull_request:
    branches:
      - main
jobs:
  packer_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.5/packer_1.8.5_linux_amd64.zip
          unzip packer_1.8.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/packer
          packer --version
        shell: bash

      - name: Install packer plugins
        run: packer plugins install github.com/hashicorp/amazon

      - name: Format Packer Template
        run: |
          set -e
          packer fmt -check ami.pkr.hcl
          echo "Packer formatting passed for ami.pkr.hcl"
      - name: Validate Packer Template
        run: |
          set -e
          packer validate ami.pkr.hcl
          echo "Validation check passed for ami.pkr.hcl"
